### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by inorton** [inorton/cclash#3]
- [x] Isolate compiler instances from environment
- [x] Server to accept more than one job (convert pipes to tcp service)
- [ ] Setting to disable stats collection
- [ ] Create monitoring tool (tcp service) for stats collection
- [ ] Spot what might get compiled next and pre-empt cache misses concurrently
